INSERT INTO users (display_name, email, avatar_path, bio, location_text, badge_label, joined_at, rating, swaps_completed, is_verified) VALUES
('Sarah Miller', 'sarah@example.com', '/public/images/users/sarah-miller.png', 'Avid reader and collector of vintage editions. I love swapping books that have moved me for new stories. Always looking for classic literature, design systems, and contemporary poetry. All my items are kept in smoke-free environments.', 'Seattle, WA', 'Power User', '2023-10-01', 4.9, 12, 1),
('Alex Record', 'alex@example.com', '/public/images/users/alex-record.png', 'Collector of records, cameras, and music history books. Happy to trade fairly and always meet in public places.', 'Portland, OR', 'Top Swapper', '2024-01-05', 4.8, 8, 1),
('Marcus Chen', 'marcus@example.com', '/public/images/users/marcus-chen.png', 'Fantasy fan, manga reader, and collector of beautifully illustrated editions.', 'Manchester, UK', 'Verified Swapper', '2024-02-12', 4.8, 15, 1),
('Elena Rodriguez', 'elena@example.com', '/public/images/users/elena-rodriguez.png', 'I enjoy jazz records, modern poetry, and community swaps that feel safe and respectful.', 'Madrid, ES', 'Trusted Member', '2023-11-20', 4.7, 4, 0),
('David Kim', 'david@example.com', '/public/images/users/david-kim.png', 'Designer, book lover, and careful collector of minimal editions and rare print finds.', 'Berlin, DE','Top Contributor', '2023-12-10', 4.9, 22, 1);

INSERT INTO items (title, author_artist, item_type, condition_note, description, image_path, gallery_image_2, gallery_image_3, gallery_image_4, location_text, owner_user_id, is_featured, created_at) VALUES
('The Hobbit', 'J.R.R. Tolkien', 'book', 'Good Condition', 'A well-kept fantasy classic with clean pages and a crisp cover.', '/public/images/items/the-hobbit-main.png', '/public/images/items/hobbit-2.jpg', '/public/images/items/hobbit-3.jpeg', '/public/images/items/hobbit-4.jpg', 'Portland, OR', 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('Kind of Blue', 'Miles Davis', 'record', 'Very Good', 'Iconic jazz album with a clean sleeve and well-preserved disc.', '/public/images/items/kind-of-blue.jpg', NULL, NULL, NULL, 'Berlin, DE', 2, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Dune', 'Frank Herbert', 'book', 'Fair Condition', 'Sci-fi staple in good reading condition with bright cover art.', '/public/images/items/dune.jpg', NULL, NULL, NULL, 'New York, US', 3, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Abbey Road', 'The Beatles', 'record', 'Good Condition', 'Classic album with strong playback quality and a sharp sleeve.', '/public/images/items/abbey-road.jpg', NULL, NULL, NULL, 'Liverpool, UK', 4, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('1984', 'George Orwell', 'book', 'Vintage', 'Vintage paperback copy with light wear and clear text.', '/public/images/items/1984.jpg', NULL, NULL, NULL, 'London, UK', 1, 0, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('The Name of the Wind', 'Patrick Rothfuss', 'book', 'Good', 'Fantasy paperback in solid condition, ideal for first-time readers.', '/public/images/items/name-of-the-wind.jpg', NULL, NULL, NULL, 'Dublin, IE', 2, 0, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('American Gods', 'Neil Gaiman', 'book', 'Good', 'Dark fantasy edition with excellent cover presentation.', '/public/images/items/american-gods.jpg', NULL, NULL, NULL, 'Leeds, UK', 3, 0, DATE_SUB(NOW(), INTERVAL 10 DAY)),
('The Witcher', 'Andrzej Sapkowski', 'book', 'Like New', 'Collector-friendly edition with sharp edges and almost no shelf wear.', '/public/images/items/the-witcher.jpg', NULL, NULL, NULL, 'Prague, CZ', 3, 0, DATE_SUB(NOW(), INTERVAL 12 DAY)),
('Mistborn', 'Brandon Sanderson', 'book', 'Mint', 'Well-kept fantasy book with a dramatic illustrated cover.', '/public/images/items/mistborn.jpg', NULL, NULL, NULL, 'Edinburgh, UK', 5, 0, DATE_SUB(NOW(), INTERVAL 14 DAY)),
('Neuromancer', 'William Gibson', 'book', 'Good', 'Cyberpunk classic in tidy condition, ideal for genre collectors.', '/public/images/items/neuromancer.jpg', NULL, NULL, NULL, 'Toronto, CA', 5, 0, DATE_SUB(NOW(), INTERVAL 15 DAY)),
('Modern Poetry Vol 1', 'Jahan Ramazani', 'book', 'Good', 'Soft neutral-toned poetry collection, clean and giftable.', '/public/images/items/modern-poetry-vol-1.jpg', NULL, NULL, NULL, 'Madrid, ES', 4, 0, DATE_SUB(NOW(), INTERVAL 16 DAY)),
('Design Systems', 'Alla Kholmatova', 'book', 'Mint', 'Design reference book in very strong condition with minimal wear.', '/public/images/items/design-systems.jpg', NULL, NULL, NULL, 'Berlin, DE', 5, 0, DATE_SUB(NOW(), INTERVAL 18 DAY));

INSERT INTO recent_swaps (title, subtitle, image_path, created_at) VALUES
('Dune for Foundation', 'Swap completed', '/public/images/items/dune.png', DATE_SUB(NOW(), INTERVAL 2 MINUTE)),
('Abbey Road vinyl swapped', 'Request accepted', '/public/images/items/abbey-road.jpg', DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
('The Hobbit traded', 'Member meetup scheduled', '/public/images/items/the-hobbit-main.png', DATE_SUB(NOW(), INTERVAL 1 HOUR));                                                           
